require:
  - rubocop-rails


AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  CacheRootDirectory: ./tmp/rubocop/
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/requests/movie_api_spec.rb'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
